### ISSUE TITLE
음성 데이터 문의

### ISSUE THREAD

**Issue by mskeum** [goodatlas/zeroth#2]
안녕하세요. 고려대 금민석입니다. 
한국어 음성인식에 큰 기여를 해주시는 점 다시 한번 감사드립니다. 
github 은 clone 만 해보았는데 issue 에 글을 올려보는 것은 처음이네요. ^^

아직 음향모델 훈련을 돌려보지는 않았는데요. 일단은 https://github.com/goodatlas/zeroth/blob/master/s5/RESULTS 에 나와있는 성능을 참고하여, 제가 연구에 사용하던 음성인식기로 AWS 에서 받은 test_data_01 데이터의 성능 확인을 해보고 비교해보려고 했는데요. 

성능이 매우 저조하게 나와서 음성데이터를 확인해보니 제가 훈련에 사용한 ETRI 음성데이터와 음향특성에 차이가 큰 것 때문이 아닌가 생각이 됩니다. 혹시 별도의 speech enhancement 가 적용되었는지 문의드립니다. 제가 훈련한 데이터가 별도의 RIR 처리를 안해서 그런 것 같기도 하네요.

**Comment by jty016** [comment]
안녕하세요, 페이스북에서 뵙고 여기서 뵙게되니 반갑습니다.
제가 이해한게 맞다면 받으신 test_data_01 데이터를 연구에 사용하시던 음성인식기로 
디코딩 테스트를 하셨다는 말씀이시지요? 
train_data_01 을 학습에 사용 것인지 궁금해서 여쭤봅니다.

일단 질문에 답을 드리면 오픈소스로 제공되는 오디오 데이터에 특별한 전처리는 되어 있지 않습니다.
다만 녹음환경은 약간의 reverb가 존재할 수 있는 작은 방의 조용한 환경인 경우가 많이 들어있을 수 있습니다.

연구용으로 가지고 계신 인식기에서 비슷한 결과를 보시려면 (아마도)
train_data_01 를 학습데이터에 포함시키시고 RIR simulation 방식의 data augmentation 을 적용하시기를 
권해드립니다. 그리고  디코딩은 test_data_01 으로 하시면 될 것 같습니다.

요즘은 음성이 들어오는 경로가 매우 다양하기 때문에  RIR 처리를 하는 것이 성능에 도움이 됩니다.

**Comment by dobby-seo** [comment]
@jty016 
안녕하세요. 음성인식 연구중인 학생입니다.
저도 비슷한 케이스로 Ai-Hub에서 공개한 데이터로 학습한 모델(CER 8%, WER 16%)을 사용하여 Zeroth Train Data는 따로 학습하지 않고 Test Data만 평가할 때, 성능이 저조하게 나오네요. 혹시 샘플레이트가 몇 으로 녹음된지 알 수 있을까요?

Zeroth Train Data로 학습(CER 8%, WER 9%)하고 역으로 Ai-Hub 데이터를 평가할 때도 성능이 잘 나오지 않는데, 오디오 파일의 정보의 차이로 보고 있습니다.

좋은 프로젝트 감사합니다!
