### ISSUE TITLE
[문의] 모아코인 음성 녹음

### ISSUE THREAD

**Issue by hairzooc** [goodatlas/zeroth#9]
안녕하세요.
모아코인 앱을 이용해서 음성 녹음을 하려고 했는데,
No open campaign found 라고 뜨며 더 이상 진행이 되지 않고 있습니다.
관련해서 확인 부탁 드릴께요.

@최신 음성 데이터를 얻을 수 있는 다른 방법이 있다면 공유해 주시면 감사하겠습니다 (__)

**Comment by jty016** [comment]
현재는 모아코인을 통한 음성 배포를 잠시  중단한 상태입니다. 2분기 중에 다시 오픈 될 수 있으니 다시 재개 되면 사이트를 통해 알려드리겠습니다.

**Comment by hairzooc** [comment]
네 알겠습니다 확인 감사 드립니다^^
